# Generated by Django 2.2.13 on 2020-07-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Framework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedassignment',
            name='grade',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('graded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff_Framework.GradedAssignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff_Framework.Question')),
            ],
        ),
    ]
