# Generated by Django 2.2.13 on 2020-07-02 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Staff_Framework', '0002_auto_20200702_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='gradedassignment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_create', to=settings.AUTH_USER_MODEL),
        ),
    ]
