# Generated by Django 2.2.13 on 2020-07-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Framework', '0003_auto_20200702_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradedassignment',
            old_name='teacher',
            new_name='student',
        ),
    ]
