# Generated by Django 2.2.13 on 2020-07-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman_Framework', '0001_initial'),
        ('Staff_Framework', '0004_auto_20200702_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='clo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Chairman_Framework.CLO'),
        ),
    ]
